version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 10
    commands:
      - echo install npm packages
      - npm install -g yarn
      - npm install -g serverless
      - yarn install
      - echo install docker
      - apt-get update
      - apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - apt-key fingerprint 0EBFCD88
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - apt-get update
      - apt-get install docker-ce docker-ce-cli containerd.io
      -
  build:
    commands:
      - echo Build to CloudFormation
      - serverless deploy -v -s $ENV_NAME
  post_build:
    commands:
      - echo Deployment completed