version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 10
    commands:
      - echo install npm packages
      - npm install -g yarn
      - npm install -g serverless
      - yarn install
      - echo install docker
      - yum update
      - yum install -y yum-utils device-mapper-persistent-data lvm2 selinux-policy selinux-policy-base selinux-policy-targeted
      - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      - yum list docker-ce --showduplicates | sort -r
      - yum-config-manager --enable rhel-7-server-extras-rpms
      - yum-config-manager --enable rhui-REGION-rhel-server-extras
      - yum install -y http://ftp.riken.jp/Linux/cern/centos/7/extras/x86_64/Packages/container-selinux-2.74-1.el7.noarch.rpm
      - yum install docker-ce-19.03.5 docker-ce-cli-19.03.5 containerd.io
      - systemctl start docker
  build:
    commands:
      - echo Build to CloudFormation
      - serverless deploy -v -s $ENV_NAME
  post_build:
    commands:
      - echo Deployment completed