version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 10
    commands:
      - echo install npm packages
      - npm install -g yarn
      - npm install -g serverless
      - yarn install
      - echo install python packages
      - pip install tushare
      - pip install statsmodels
      - pip install lxml
      - pip install requests
      - pip install bs4
  build:
    commands:
      - echo Build to CloudFormation
      - serverless deploy -v -s $ENV_NAME
  post_build:
    commands:
      - echo Deployment completed