service: invest-valid-serverless-python

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-southeast-1
  memorySize: 256
  timeout: 300

plugins:
  - serverless-offline
  - serverless-python-requirements

package:
  individually: true

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true

functions:
  similarity_compute:
    handler: similarity_compute.similarity_compute
    module: Statistics
    events:
      - http:
          path: statistics/similarity_compute
          method: post
          cors: true
