service: invest-valid-serverless-python

provider:
  name: aws
  runtime: python3.7
  region: ap-southeast-1
  memorySize: 256
  timeout: 300
  environment:
    COPORA_TABLE: ${self:custom.coporaTable}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        "Fn::GetAtt": [ CoporaDynamoDbTable, Arn ]

plugins:
  - serverless-offline
  - serverless-python-requirements

package:
  individually: true

custom:
  coporaTable:
    Ref: CoporaDynamoDbTable
  pythonRequirements:
    dockerizePip: true
    slim: true
  allowedHeaders:
    - Accept
    - Content-Type
    - Content-Length
    - Authorization
    - X-Amz-Date
    - X-Api-key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    - Access-Control-Allow-Origin

functions:
  similarity_compute:
    handler: similarity_compute.similarity_compute
    module: Statistics
    environment:
      TUSHARE_TOKEN: ${env:TUSHARE_TOKEN}
    events:
      - http:
          path: statistics/similarity_compute
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

resources:
  Resources:
    CoporaDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: corpora_id
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: corpora_id
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:service}-copora-${opt:stage}
