service: invest-valid-serverless-python

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-southeast-1
  memorySize: 256
  timeout: 300

plugins:
  - serverless-offline

functions:
  similarity_compute:
    handler: Statistics.similarity_compute.similarity_compute
    events:
      - http:
          path: statistics/similarity_compute
          method: post
          cors: true
